### ISSUE TITLE
Screen Glitches

### ISSUE THREAD

**Issue by SHABRAWii** [navaismo/Ender-3V3-SE#4]
I did follow all the steps in [this issue](https://github.com/navaismo/Ender-3V3-SE/issues/2#issuecomment-2456061774) and I still have glitches with the LCD.

> ![Image](https://github.com/user-attachments/assets/3a5d3be0-18d9-42c5-8d27-a3ba3efdb993)

**Comment by navaismo** [comment]
It looks like you have another plugin sending M117 commands to the printer and thats why you see both screens overlaping, If you want to see only M117 commands from other plugins then use the Firmware from Main Branch. I f you want to see the Print Job Details then disable plugins that send M117 commands to the printer.
